= ISO Rice document in vanilla Metanorma (Metanorma-standoc)

This document is available in its rendered forms here:

https://kickoke.github.io/mn-samples-standoc/[Rice document (repository)]

== Introduction

This repository provides a readily usable  https://github.com/metanorma/metanorma-iso[Metanorma-Standoc]
source document based on the
https://www.iso.org/publication/PUB100407.html["`Rice document`"],
the ISO's model document of an international standard.



== Fetching the document

[source,sh]
----
git clone https://github.com/metanorma/mn-samples-standoc/
----

== Installing Build Tools

See https://www.metanorma.org/install/[Metanorma documentation]


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker:

[source,sh]
----
docker run -v "$(pwd)":/metanorma -w /metanorma -it metanorma/mn metanorma site generate
----


== Building The Document

[source,sh]
----
metanorma site generate
----


== Source files provided in this repo

* `document.adoc`: Metanorma Asciidoc markup source document for the Rice document, referencing the individual files in `sections/*`

* `sections/*`: The Metanorma-ISO markup source document for the Rice document, broken up into separate files for each section


== Description of generated artifacts

* `{filename}-{lang}.xml`: Metanorma XML output corresponding to the `{filename}-{lang}.adoc` source

* `{filename}-{lang}.html`: Metanorma HTML output corresponding to the `{filename}-{lang}.adoc` source

* `{filename}-{lang}-alt.html`: Metanorma "`readability-optimized`" HTML output corresponding to the `{filename}-{lang}.adoc` source



=== Building a document from multiple files

The document `document.adoc` includes the document header and the following files.

The section files are listed in order of appearance in the document, and each corresponds to a first-level clause of the Rice document:

* `00-foreword.adoc`: Foreword
* `00-introduction.adoc`: Introduction
* `01-scope.adoc`: Scope
* `02-normref.adoc`: Normative references
* `03-termdef.adoc`: Terms and definitions
* `04-specifications.adoc`: Clause 4: Specifications
* `05-sampling.adoc`: Clause 5: Sampling
* `06-testmethods.adoc`: Clause 6: Test Methods
* `07-testreport.adoc`: Clause 7: Test Report
* `08-packaging.adoc`: Clause 8: Packaging
* `09-marking.adoc`: Clause 9: Marking
* `aa-annex-a.adoc`: Annex A
* `ab-annex-b.adoc`: Annex B
* `ac-annex-c.adoc`: Annex C
* `ad-annex-d.adoc`: Annex D
* `ae-annex-e.adoc`: Annex E (not in original Rice document, included to illustrate further formatting options)
* `b0-bibliography.adoc`: Bibliography

