[[AnnexD]]
[appendix,obligation=informative]
== Results of interlaboratory test for husked rice yields

An interlaboratory test <<ref15, fn>> was carried out by the ENR [Rice Research Centre (Italy)] in accordance with <<ISO5725-1>> and <<ISO5725-2>>, with the participation of 15 laboratories. Each laboratory carried out three determinations on four different types of kernel. The statistical results are shown in <<tableD-1>>.

[[tableD-1]]
[cols="<,^,^,^,^",headerrows=2]
.Repeatability and reproducibility of husked rice yield
|===
.2+^| Description 4+| Rice sample
| Arborio | Drago footnote:[Parboiled rice.] | Balilla | Thaibonnet

| Number of laboratories retained after eliminating outliers | 13 | 11 | 13 | 13
| Mean value, g/100 g | 81,2 | 82,0 | 81,8 | 77,7
| Standard deviation of repeatability, stem:[s_r], g/100 g | 0,41 | 0,15 | 0,31 | 0,53
| Coefficient of variation of repeatability, % | 0,5 | 0,2 | 0,4 | 0,7
| Repeatability limit, stem:[r] (= 2,83 stem:[s_r]) | 1,16 | 0,42 | 0,88 | 1,50
| Standard deviation of reproducibility, stem:[s_R], g/100 g | 1,02 | 0,20 | 0,80 | 2,14
| Coefficient of variation of reproducibility, % | 1,3 | 0,2 | 1,0 | 2,7
| Reproducibility limit, stem:[R] (= 2,83 stem:[s_R]) | 2,89 | 0,57 | 2,26 | 6,06
|===

[appendix,obligation=informative]
== Extraneous information

_This appendix is not in the original Rice model document, and is inserted to illustrate elements absent from
that document: block quotes, source code, and examples._

[quote, ISO, "ISO7301,clause 1"]
_____
This International Standard gives the minimum specifications for rice (_Oryza sativa_ L.) which is subject to international trade. It is applicable to the following types: husked rice and milled rice, parboiled or not, intended for direct human consumption. It is neither applicable to other products derived from rice, nor to waxy rice (glutinous rice).
_____

[%appendix]
=== Sample code

[[samplecode]]
.Sample Code
====

[source,ruby]
--
puts "Hello, world."
%w{a b c}.each do |x| <1>
  puts x
end
--
<1> This is an annotation
====